### ISSUE TITLE
MEM_JAVA_PERCENT, how does it work

### ISSUE THREAD

**Issue by jbellmann** [zalando-zmon/zmon-kubernetes#2]
After 'deployments' generated by script, I see the following in the containers 'env'-section

```
          - name: "MEM_JAVA_PERCENT"
            value: |-
              25
```

How does this work?

**Comment by hjacobs** [comment]
This is the setting from our base Docker image, see https://github.com/zalando/docker-openjdk/blob/master/utils/java-dynamic-memory-opts

**Comment by jbellmann** [comment]
Thanks.
